### ISSUE TITLE
mdbroker example does not always purge disconnected workers

### ISSUE THREAD

**Issue by Djuke** [pebbe/zmq4#43]
The comment at the Purge method states that it deletes idle workers that haven't pinged the broker. But lets say two workers connect to the broker and none of them gets any work.
W 1: connects, and is appended to the broker's waiting list and service's waiting list
W 2: connects, and is appended to the broker's waiting list and service's waiting list

When W 2 disconnects it will not be purged because the Purge method stops as soon as it finds a worker that is not expired. If W 1 send its heartbeats on time the Purge method will never reach W 2.

Then if a client sends a request to be processed by a service as W 2 and W 2 is the only one who is listed, but disconnected, the request is sent to W 2 and no error returns.

**Comment by pebbe** [comment]
I'm not sure what is going on. It's been a long time since I wrote this.
It seems that, once W 1 gets a job, it is popped from the waiting list, then W 2 is at the front, and it will be purged.

This is just a rewrite in Go of the original example written in C. Do you think the Go version is an incorrect rewrite of the C version?
http://zguide.zeromq.org/page:all#toc98

If your comment applies to the C version as well, you should discuss it on the ZeroMQ maling list:
http://zeromq.org/docs:mailing-lists

**Comment by catinred2** [comment]
@Djuke  Plz check this out. https://github.com/catinred2/zguide/commit/f467269b7e565ebbaab3cb7be126092414bb4ba4 It's java,but you can easily rewrite it in Go.

**Comment by Djuke** [comment]
@pebbe I found that the implementation is missing intentionally. This is from http://zguide.zeromq.org/page:all#toc98

> Now let's design the Majordomo broker. Its core structure is a set of queues, one per service. We will create these queues as workers appear (we could delete them as workers disappear, but forget that for now because it gets complex). Additionally, we keep a queue of workers per service.

So the mdbroker example is fine as it is. 

@catinred2 Tnx for the info.
